id = "slash-commands-example1"
name = "Slash Commands Example1"
description = "An example extension showcasing slash commands."
version = "0.1.0"
schema_version = 1
authors = ["ericbuess@gmail.com"]
repository = "https://github.com/ericbuess/zed-slash-ext.git"

[slash_commands.echo]
description = "echoes the provided input"
requires_argument = true

[slash_commands.pick-one]
description = "pick one of three options"
requires_argument = true
